### ISSUE TITLE
Cannot login (self-hosted or x2.email)

### ISSUE THREAD

**Issue by gregg098** [jessetinell/x2.email#1]
I cloned the repository and got things running on a Debian container, but as soon as I click the "Connect to Cloudflare" button, nothing happens. When I load other pages, I see status messages like this:

```
- wait compiling /login/page (client and server)...
- event compiled client and server successfully in 3.1s (2615 modules)
```
But after clicking the "Connect to Cloudflare" button, I dont see anything change. The page isnt trying load, nothing.

I tried the same tokens on x2.email and had the same result. As a final check, I tried Firefox (vs Chrome), and also got the same result.

I have verified the api token has the correct permissions and that I am using the correct account/zone ids.

Any ideas?

**Comment by jessetinell** [comment]
I haven't tried Debian containers. Could be something there. 
Try debugging the `authorize` function in `UserContext.tsx` to see what happens there. Or the `onSubmit` in `Authentication.tsx`.
