### ISSUE TITLE
List of email addresses is truncated at 20

### ISSUE THREAD

**Issue by sendmebits** [jessetinell/x2.email#3]
I have 48 email aliases created, however, only 20 show on the screen. This causes some issues if I'm trying to verify which aliases I have created already before creating a new one or I'm trying to edit an alias that is only than the 20th newest item.

Adding pagination, infinite scroll or even a search option would help solve this use case. A very simple search would be welcome either way :)

Thanks for the great tool, I find it very useful!

**Comment by jessetinell** [comment]
Glad you like it! I've just pushed a fix to fetch all aliases.
